apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-app
  namespace: api-dev
spec:
  selector:
    matchLabels:
      app: user-java-app
  template:
    metadata:
      labels:
        app: user-java-app
    spec:
      containers:
      - name: user-java
        image: registrybal1640.azurecr.io/user-java
        env:
          - name: SQL_USER
            value: "sqladminbAl1640"
          - name: SQL_PASSWORD
            value: "jM59p4Ul0"
          - name: SQL_SERVER
            value: "mydrivingDB.database.windows.net"
          - name: SQL_DBNAME
            value: "mydrivingDB"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: user-java-app-service
  namespace: api-dev
spec:
  selector:
    app: user-java-app
  ports:
  - port: 80
    targetPort: 8080

        
